// Quranic verses for each prayer
export const prayerVerses = {
  Fajr: [
    { arabic: "إِنَّ قُرْآنَ الْفَجْرِ كَانَ مَشْهُودًا", english: "Indeed, the recitation at dawn is ever witnessed.", ref: "17:78" },
    { arabic: "وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ الشَّمْسِ", english: "Glorify the praises of your Lord before the rising of the sun.", ref: "50:39" },
    { arabic: "وَالصُّبْحِ إِذَا تَنَفَّسَ", english: "And by the dawn as it breathes.", ref: "81:18" },
  ],
  Dhuhr: [
    { arabic: "حَافِظُوا عَلَى الصَّلَوَاتِ وَالصَّلَاةِ الْوُسْطَىٰ", english: "Maintain with care the prayers and the middle prayer.", ref: "2:238" },
    { arabic: "إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَّوْقُوتًا", english: "Indeed, prayer is an obligation for believers at prescribed times.", ref: "4:103" },
    { arabic: "قَدْ أَفْلَحَ الْمُؤْمِنُونَ الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ", english: "Successful are the believers who are humble in their prayers.", ref: "23:1-2" },
  ],
  Asr: [
    { arabic: "وَالْعَصْرِ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ", english: "By time, indeed mankind is in loss.", ref: "103:1-2" },
    { arabic: "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ", english: "Except those who believe and do righteous deeds.", ref: "103:3" },
    { arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", english: "Seek help through patience and prayer.", ref: "2:45" },
  ],
  Maghrib: [
    { arabic: "وَسَبِّحُوهُ بُكْرَةً وَأَصِيلًا", english: "And glorify Him in the morning and the evening.", ref: "33:42" },
    { arabic: "فَسُبْحَانَ اللَّهِ حِينَ تُمْسُونَ وَحِينَ تُصْبِحُونَ", english: "So glorify Allah when you reach the evening and the morning.", ref: "30:17" },
    { arabic: "أَقِمِ الصَّلَاةَ لِدُلُوكِ الشَّمْسِ إِلَىٰ غَسَقِ اللَّيْلِ", english: "Establish prayer at the decline of the sun until the darkness of the night.", ref: "17:78" },
  ],
  Isha: [
    { arabic: "وَمِنَ اللَّيْلِ فَسَبِّحْهُ وَأَدْبَارَ السُّجُودِ", english: "And from the night, glorify Him, and after prostration.", ref: "50:40" },
    { arabic: "وَمِنَ اللَّيْلِ فَتَهَجَّدْ بِهِ نَافِلَةً لَّكَ", english: "And from the night, pray with it as additional worship for you.", ref: "17:79" },
    { arabic: "تَتَجَافَىٰ جُنُوبُهُمْ عَنِ الْمَضَاجِعِ", english: "Their sides part from their beds to supplicate their Lord.", ref: "32:16" },
  ],
};

// All 114 Surahs
export const surahs = [
  { number: 1, arabic: "الفاتحة", english: "Al-Fatihah", ayahs: 7 },
  { number: 2, arabic: "البقرة", english: "Al-Baqarah", ayahs: 286 },
  { number: 3, arabic: "آل عمران", english: "Ali 'Imran", ayahs: 200 },
  { number: 4, arabic: "النساء", english: "An-Nisa", ayahs: 176 },
  { number: 5, arabic: "المائدة", english: "Al-Ma'idah", ayahs: 120 },
  { number: 6, arabic: "الأنعام", english: "Al-An'am", ayahs: 165 },
  { number: 7, arabic: "الأعراف", english: "Al-A'raf", ayahs: 206 },
  { number: 8, arabic: "الأنفال", english: "Al-Anfal", ayahs: 75 },
  { number: 9, arabic: "التوبة", english: "At-Tawbah", ayahs: 129 },
  { number: 10, arabic: "يونس", english: "Yunus", ayahs: 109 },
  { number: 11, arabic: "هود", english: "Hud", ayahs: 123 },
  { number: 12, arabic: "يوسف", english: "Yusuf", ayahs: 111 },
  { number: 13, arabic: "الرعد", english: "Ar-Ra'd", ayahs: 43 },
  { number: 14, arabic: "إبراهيم", english: "Ibrahim", ayahs: 52 },
  { number: 15, arabic: "الحجر", english: "Al-Hijr", ayahs: 99 },
  { number: 16, arabic: "النحل", english: "An-Nahl", ayahs: 128 },
  { number: 17, arabic: "الإسراء", english: "Al-Isra", ayahs: 111 },
  { number: 18, arabic: "الكهف", english: "Al-Kahf", ayahs: 110 },
  { number: 19, arabic: "مريم", english: "Maryam", ayahs: 98 },
  { number: 20, arabic: "طه", english: "Ta-Ha", ayahs: 135 },
  { number: 21, arabic: "الأنبياء", english: "Al-Anbiya", ayahs: 112 },
  { number: 22, arabic: "الحج", english: "Al-Hajj", ayahs: 78 },
  { number: 23, arabic: "المؤمنون", english: "Al-Mu'minun", ayahs: 118 },
  { number: 24, arabic: "النور", english: "An-Nur", ayahs: 64 },
  { number: 25, arabic: "الفرقان", english: "Al-Furqan", ayahs: 77 },
  { number: 26, arabic: "الشعراء", english: "Ash-Shu'ara", ayahs: 227 },
  { number: 27, arabic: "النمل", english: "An-Naml", ayahs: 93 },
  { number: 28, arabic: "القصص", english: "Al-Qasas", ayahs: 88 },
  { number: 29, arabic: "العنكبوت", english: "Al-'Ankabut", ayahs: 69 },
  { number: 30, arabic: "الروم", english: "Ar-Rum", ayahs: 60 },
  { number: 31, arabic: "لقمان", english: "Luqman", ayahs: 34 },
  { number: 32, arabic: "السجدة", english: "As-Sajdah", ayahs: 30 },
  { number: 33, arabic: "الأحزاب", english: "Al-Ahzab", ayahs: 73 },
  { number: 34, arabic: "سبأ", english: "Saba", ayahs: 54 },
  { number: 35, arabic: "فاطر", english: "Fatir", ayahs: 45 },
  { number: 36, arabic: "يس", english: "Ya-Sin", ayahs: 83 },
  { number: 37, arabic: "الصافات", english: "As-Saffat", ayahs: 182 },
  { number: 38, arabic: "ص", english: "Sad", ayahs: 88 },
  { number: 39, arabic: "الزمر", english: "Az-Zumar", ayahs: 75 },
  { number: 40, arabic: "غافر", english: "Ghafir", ayahs: 85 },
  { number: 41, arabic: "فصلت", english: "Fussilat", ayahs: 54 },
  { number: 42, arabic: "الشورى", english: "Ash-Shura", ayahs: 53 },
  { number: 43, arabic: "الزخرف", english: "Az-Zukhruf", ayahs: 89 },
  { number: 44, arabic: "الدخان", english: "Ad-Dukhan", ayahs: 59 },
  { number: 45, arabic: "الجاثية", english: "Al-Jathiyah", ayahs: 37 },
  { number: 46, arabic: "الأحقاف", english: "Al-Ahqaf", ayahs: 35 },
  { number: 47, arabic: "محمد", english: "Muhammad", ayahs: 38 },
  { number: 48, arabic: "الفتح", english: "Al-Fath", ayahs: 29 },
  { number: 49, arabic: "الحجرات", english: "Al-Hujurat", ayahs: 18 },
  { number: 50, arabic: "ق", english: "Qaf", ayahs: 45 },
  { number: 51, arabic: "الذاريات", english: "Adh-Dhariyat", ayahs: 60 },
  { number: 52, arabic: "الطور", english: "At-Tur", ayahs: 49 },
  { number: 53, arabic: "النجم", english: "An-Najm", ayahs: 62 },
  { number: 54, arabic: "القمر", english: "Al-Qamar", ayahs: 55 },
  { number: 55, arabic: "الرحمن", english: "Ar-Rahman", ayahs: 78 },
  { number: 56, arabic: "الواقعة", english: "Al-Waqi'ah", ayahs: 96 },
  { number: 57, arabic: "الحديد", english: "Al-Hadid", ayahs: 29 },
  { number: 58, arabic: "المجادلة", english: "Al-Mujadila", ayahs: 22 },
  { number: 59, arabic: "الحشر", english: "Al-Hashr", ayahs: 24 },
  { number: 60, arabic: "الممتحنة", english: "Al-Mumtahanah", ayahs: 13 },
  { number: 61, arabic: "الصف", english: "As-Saf", ayahs: 14 },
  { number: 62, arabic: "الجمعة", english: "Al-Jumu'ah", ayahs: 11 },
  { number: 63, arabic: "المنافقون", english: "Al-Munafiqun", ayahs: 11 },
  { number: 64, arabic: "التغابن", english: "At-Taghabun", ayahs: 18 },
  { number: 65, arabic: "الطلاق", english: "At-Talaq", ayahs: 12 },
  { number: 66, arabic: "التحريم", english: "At-Tahrim", ayahs: 12 },
  { number: 67, arabic: "الملك", english: "Al-Mulk", ayahs: 30 },
  { number: 68, arabic: "القلم", english: "Al-Qalam", ayahs: 52 },
  { number: 69, arabic: "الحاقة", english: "Al-Haqqah", ayahs: 52 },
  { number: 70, arabic: "المعارج", english: "Al-Ma'arij", ayahs: 44 },
  { number: 71, arabic: "نوح", english: "Nuh", ayahs: 28 },
  { number: 72, arabic: "الجن", english: "Al-Jinn", ayahs: 28 },
  { number: 73, arabic: "المزمل", english: "Al-Muzzammil", ayahs: 20 },
  { number: 74, arabic: "المدثر", english: "Al-Muddaththir", ayahs: 56 },
  { number: 75, arabic: "القيامة", english: "Al-Qiyamah", ayahs: 40 },
  { number: 76, arabic: "الإنسان", english: "Al-Insan", ayahs: 31 },
  { number: 77, arabic: "المرسلات", english: "Al-Mursalat", ayahs: 50 },
  { number: 78, arabic: "النبأ", english: "An-Naba", ayahs: 40 },
  { number: 79, arabic: "النازعات", english: "An-Nazi'at", ayahs: 46 },
  { number: 80, arabic: "عبس", english: "Abasa", ayahs: 42 },
  { number: 81, arabic: "التكوير", english: "At-Takwir", ayahs: 29 },
  { number: 82, arabic: "الانفطار", english: "Al-Infitar", ayahs: 19 },
  { number: 83, arabic: "المطففين", english: "Al-Mutaffifin", ayahs: 36 },
  { number: 84, arabic: "الانشقاق", english: "Al-Inshiqaq", ayahs: 25 },
  { number: 85, arabic: "البروج", english: "Al-Buruj", ayahs: 22 },
  { number: 86, arabic: "الطارق", english: "At-Tariq", ayahs: 17 },
  { number: 87, arabic: "الأعلى", english: "Al-A'la", ayahs: 19 },
  { number: 88, arabic: "الغاشية", english: "Al-Ghashiyah", ayahs: 26 },
  { number: 89, arabic: "الفجر", english: "Al-Fajr", ayahs: 30 },
  { number: 90, arabic: "البلد", english: "Al-Balad", ayahs: 20 },
  { number: 91, arabic: "الشمس", english: "Ash-Shams", ayahs: 15 },
  { number: 92, arabic: "الليل", english: "Al-Layl", ayahs: 21 },
  { number: 93, arabic: "الضحى", english: "Ad-Duha", ayahs: 11 },
  { number: 94, arabic: "الشرح", english: "Ash-Sharh", ayahs: 8 },
  { number: 95, arabic: "التين", english: "At-Tin", ayahs: 8 },
  { number: 96, arabic: "العلق", english: "Al-'Alaq", ayahs: 19 },
  { number: 97, arabic: "القدر", english: "Al-Qadr", ayahs: 5 },
  { number: 98, arabic: "البينة", english: "Al-Bayyinah", ayahs: 8 },
  { number: 99, arabic: "الزلزلة", english: "Az-Zalzalah", ayahs: 8 },
  { number: 100, arabic: "العاديات", english: "Al-'Adiyat", ayahs: 11 },
  { number: 101, arabic: "القارعة", english: "Al-Qari'ah", ayahs: 11 },
  { number: 102, arabic: "التكاثر", english: "At-Takathur", ayahs: 8 },
  { number: 103, arabic: "العصر", english: "Al-'Asr", ayahs: 3 },
  { number: 104, arabic: "الهمزة", english: "Al-Humazah", ayahs: 9 },
  { number: 105, arabic: "الفيل", english: "Al-Fil", ayahs: 5 },
  { number: 106, arabic: "قريش", english: "Quraysh", ayahs: 4 },
  { number: 107, arabic: "الماعون", english: "Al-Ma'un", ayahs: 7 },
  { number: 108, arabic: "الكوثر", english: "Al-Kawthar", ayahs: 3 },
  { number: 109, arabic: "الكافرون", english: "Al-Kafirun", ayahs: 6 },
  { number: 110, arabic: "النصر", english: "An-Nasr", ayahs: 3 },
  { number: 111, arabic: "المسد", english: "Al-Masad", ayahs: 5 },
  { number: 112, arabic: "الإخلاص", english: "Al-Ikhlas", ayahs: 4 },
  { number: 113, arabic: "الفلق", english: "Al-Falaq", ayahs: 5 },
  { number: 114, arabic: "الناس", english: "An-Nas", ayahs: 6 },
];

// Evening Adhkar
export const eveningAdhkar = [
  { arabic: "سُبْحَانَ اللَّهِ", transliteration: "SubhanAllah", translation: "Glory be to Allah", count: 33 },
  { arabic: "الْحَمْدُ لِلَّهِ", transliteration: "Alhamdulillah", translation: "Praise be to Allah", count: 33 },
  { arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", translation: "Allah is the Greatest", count: 34 },
  { arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimatillahi at-tammati min sharri ma khalaq", translation: "I seek refuge in the perfect words of Allah from the evil of what He has created", count: 3 },
  { arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا", transliteration: "Allahumma bika amsayna wa bika asbahna", translation: "O Allah, by You we enter the evening and by You we enter the morning", count: 1 },
  { arabic: "آيَةُ الْكُرْسِيّ", transliteration: "Ayatul Kursi", translation: "Verse of the Throne (Al-Baqarah 2:255)", count: 1 },
];

// Night Adhkar  
export const nightAdhkar = [
  { arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismika Allahumma amutu wa ahya", translation: "In Your name, O Allah, I die and I live", count: 1 },
  { arabic: "سُبْحَانَ اللَّهِ", transliteration: "SubhanAllah", translation: "Glory be to Allah", count: 33 },
  { arabic: "الْحَمْدُ لِلَّهِ", transliteration: "Alhamdulillah", translation: "Praise be to Allah", count: 33 },
  { arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", translation: "Allah is the Greatest", count: 34 },
  { arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ", transliteration: "Allahumma ighfir li dhanbi kullahu", translation: "O Allah, forgive all my sins", count: 1 },
  { arabic: "آيَةُ الْكُرْسِيّ", transliteration: "Ayatul Kursi", translation: "Verse of the Throne (Al-Baqarah 2:255)", count: 1 },
];

// Motivational quotes
export const motivationalQuotes = [
  { text: "Verily, with hardship comes ease.", source: "Quran 94:5" },
  { text: "And He found you lost and guided you.", source: "Quran 93:7" },
  { text: "Allah does not burden a soul beyond that it can bear.", source: "Quran 2:286" },
  { text: "Indeed, Allah is with the patient.", source: "Quran 2:153" },
  { text: "The best of deeds is that which is done consistently, even if small.", source: "Prophet Muhammad ﷺ" },
  { text: "Take advantage of five before five: youth before old age, health before sickness.", source: "Prophet Muhammad ﷺ" },
  { text: "Whoever fears Allah, He will make for him a way out.", source: "Quran 65:2" },
  { text: "And put your trust in Allah. Allah is sufficient as a trustee.", source: "Quran 33:3" },
  { text: "Do good, for Allah loves those who do good.", source: "Quran 2:195" },
  { text: "Your Lord has not forsaken you, nor has He become displeased.", source: "Quran 93:3" },
  { text: "Seek help through patience and prayer.", source: "Quran 2:45" },
  { text: "He who does an atom's weight of good shall see it.", source: "Quran 99:7" },
  { text: "When you wake up thinking about a goal, that is a sign it was meant for you.", source: "Wisdom" },
  { text: "Start where you are. Use what you have. Do what you can.", source: "Wisdom" },
  { text: "Excellence is not a skill, it's an attitude.", source: "Wisdom" },
  { text: "Small steps forward are still steps forward.", source: "Wisdom" },
  { text: "The secret of getting ahead is getting started.", source: "Wisdom" },
  { text: "Make dua before you start, and gratitude when you finish.", source: "Islamic Wisdom" },
  { text: "Bismillah — with the name of Allah, begin.", source: "Islamic Practice" },
  { text: "Consistency is more important than intensity.", source: "Wisdom" },
];

export const prayerNames = ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];

export const prayerStatuses = {
  PRAYED: { label: 'Prayed', emoji: '✅', color: 'var(--emerald)' },
  MASJID: { label: 'Masjid', emoji: '🕌', color: 'var(--gold)' },
  MISSED: { label: 'Missed', emoji: '❌', color: 'var(--coral)' },
  QADHA: { label: "Qadha", emoji: '⏳', color: 'var(--purple)' },
  PENDING: { label: 'Pending', emoji: '⏱️', color: 'var(--text-dim)' },
};
